export const gridPositions = [
  {
    position: "top-left",
    icon: "fluent:arrow-step-over-20-filled",
    rotate: -90,
    row: 1,
    column: 2,
  },
  {
    position: "top",
    icon: "fluent:arrow-step-out-20-filled",
    row: 1,
    column: 3,
  },
  {
    position: "top-right",
    icon: "fluent:arrow-step-back-20-filled",
    rotate: 90,
    row: 1,
    column: 4,
  },
  {
    position: "right-top",
    icon: "fluent:arrow-step-over-20-filled",
    row: 2,
    column: 5,
  },
  {
    position: "right",
    icon: "fluent:arrow-step-out-20-filled",
    rotate: 90,
    row: 3,
    column: 5,
  },
  {
    position: "right-bottom",
    icon: "fluent:arrow-step-back-20-filled",
    rotate: 180,
    row: 4,
    column: 5,
  },
  {
    position: "bottom-right",
    icon: "fluent:arrow-step-over-20-filled",
    rotate: 90,
    row: 5,
    column: 4,
  },
  {
    position: "bottom",
    icon: "fluent:arrow-step-out-20-filled",
    rotate: 180,
    row: 5,
    column: 3,
  },
  {
    position: "bottom-left",
    icon: "fluent:arrow-step-back-20-filled",
    rotate: -90,
    row: 5,
    column: 2,
  },
  {
    position: "left-bottom",
    icon: "fluent:arrow-step-over-20-filled",
    rotate: 180,
    row: 4,
    column: 1,
  },
  {
    position: "left",
    icon: "fluent:arrow-step-out-20-filled",
    rotate: -90,
    row: 3,
    column: 1,
  },
  {
    position: "left-top",
    icon: "fluent:arrow-step-back-20-filled",
    row: 2,
    column: 1,
  },
  {
    position: "center",
    icon: "material-symbols-light:center-focus-weak",
    row: 3,
    column: 3,
  },
];
